apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apartments.fullname" . }}
  labels:
    {{- include "apartments.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "apartments.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "apartments.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "apartments.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /go/src/app/main
            - "-port"
            - "80"
            - "-nats"
            - "apartments-nats-client:4222"
            - "-mongo"
            - "mongodb://{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.rootPassword }}@apartments-mongodb:27017/{{ .Values.mongodb.auth.database }}"
          ports:
            - name: http
              containerPort: 50051
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 35
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 35
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
